//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace FT_PurchasingPortal.Web
{


    public partial class FindDialogTemplateContent1
    {

        /// <summary>
        /// UPPopupWindowControl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DevExpress.ExpressApp.Web.Templates.XafUpdatePanel UPPopupWindowControl;

        /// <summary>
        /// PopupWindowControl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DevExpress.ExpressApp.Web.Controls.XafPopupWindowControl PopupWindowControl;

        /// <summary>
        /// UPSAC control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DevExpress.ExpressApp.Web.Templates.XafUpdatePanel UPSAC;

        /// <summary>
        /// SAC control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DevExpress.ExpressApp.Web.Templates.ActionContainers.ActionContainerHolder SAC;

        /// <summary>
        /// UPEI control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DevExpress.ExpressApp.Web.Templates.XafUpdatePanel UPEI;

        /// <summary>
        /// ErrorInfo control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DevExpress.ExpressApp.Web.Templates.Controls.ErrorInfoControl ErrorInfo;

        /// <summary>
        /// UPVSC control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DevExpress.ExpressApp.Web.Templates.XafUpdatePanel UPVSC;

        /// <summary>
        /// VSC control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DevExpress.ExpressApp.Web.Controls.ViewSiteControl VSC;

        /// <summary>
        /// UPOC control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DevExpress.ExpressApp.Web.Templates.XafUpdatePanel UPOC;

        /// <summary>
        /// OC control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DevExpress.ExpressApp.Web.Templates.ActionContainers.ActionContainerHolder OC;

        /// <summary>
        /// XafUpdatePanel2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DevExpress.ExpressApp.Web.Templates.XafUpdatePanel XafUpdatePanel2;

        /// <summary>
        /// PopupActions control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DevExpress.ExpressApp.Web.Templates.ActionContainers.ActionContainerHolder PopupActions;
    }
}
